article/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin

urlpatterns = [
    url(r'^$', views.homepage, name='index'),
    url(r'^register/login$', views.user_login, name='user_login'),
    url(r'^index/$', views.user_logout, name='user_logout'),
    url(r'^register/post$', views.post_email,name='post_email'),
    url(r'^register/register$', views.register, name='user_register'),
    url(r'^emailfind/login', views.emailLogin,name='email_login'),
    url(r'^emailfind/post', views.post_email_login,name='login_post_email'),
    url(r'^newarticle/', views.publishArticle, name='new_article'),
    url(r'^show_article/(?P<article_id>[0-9]+)/$', views.article, name='show_article'),
    url(r'^article_list/(?P<category_id>[0-9]+)/$', views.category, name='article_list'),
    url(r'^show_article/collect$', views.collected, name='collected'),
    url(r'^myposts', views.getmyarticle, name='myarticle'),
    url(r'^mycollects', views.getmycollect, name='mycollect'),
    url(r'^myinfo', views.myinfo, name='myinfomation'),
    url(r'^download/(?P<article_id>[0-9]+)/$', views.downloadfile, name='download'),
    url(r'^show_article/subcom', views.submit_comment, name='submitcomment'),
    url(r'^show_article/subreply', views.submit_reply, name='submitreply'),
    url(r'search', views.search, name='search'),
    url(r'^resetpwd', views.resetpwd, name='reset_pwd'),
]

bbs/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('article.urls', namespace='article', app_name='article')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
]

article/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.timezone import now
from .models import *

class LoginForm(forms.Form):
    user_name = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=16, widget=forms.TextInput(attrs={'id': 'userName'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'id': 'password'}), min_length=8, max_length=20)
    email = forms.CharField(widget=forms.TextInput(attrs={'id': 'email'}))

    class Meta:
        model = User
        fields = ("username","password","email")


class IdenCodeForm(forms.Form):
    iden_code = forms.CharField(label="验证码", max_length=6,min_length=6,widget=forms.TextInput(attrs={"id":"code"}))


class EmailLoginForm(forms.Form):
    user_name = forms.CharField(label="用户名",max_length=16, widget=forms.TextInput(attrs={"id":"loginuser"}))
    code = forms.CharField(label="验证码",max_length=6,min_length=6,widget=forms.TextInput)


class AriclesForm(forms.ModelForm):
    category = forms.ModelChoiceField(required=True, queryset=Category.objects.all(),empty_label="请选择分类")
    body = forms.CharField(widget=forms.Textarea(attrs={"id":"text1","class":"hidden"}))

    class Meta:
        model = Articles
        fields = ("title", "abstract", "attachment", "body",)


class PersonalInfoForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"readonly": "true"}))
    email = forms.CharField(widget=forms.TextInput)
    born = forms.DateField(widget=forms.DateInput(attrs={"type":"date"}))
    college = forms.ModelChoiceField(required=True, queryset=College.objects.all(), empty_label="请选择学院")
    intro = forms.CharField(widget=forms.TextInput)
    sex = forms.ChoiceField(label="性别",widget=forms.RadioSelect(), choices=PersonalInfo.sex_choice)

    class Meta:
        model = PersonalInfo
        fields = ("sex",)


class ResetPwdForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"readonly":"true"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"id":"pwd1"}))
    cpassword = forms.CharField(widget=forms.PasswordInput(attrs={"id":"pwd2"}))

    def clean_cpassword(self):
        cd = self.cleaned_data
        if cd['password'] != cd['cpassword']:
            raise forms.ValidationError("passwords do not match")
        return cd['cpassword']

article/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .forms import *
import json, re, random, time, os
from django.core.mail import send_mail
from django.contrib.auth.backends import ModelBackend
from django.http import StreamingHttpResponse


# Create your views here.

def getIndexContent():
    newc = Articles.objects.all()[:8]
    hotc = Articles.objects.order_by("-views")[:8]
    tag = Category.objects.order_by("created_time").all()
    f1 = CarouselImg.objects.get(id=1)
    f2 = CarouselImg.objects.get(id=2)
    f3 = CarouselImg.objects.get(id=3)
    f4 = CarouselImg.objects.get(id=4)
    newf = {"newc": newc, "hotc": hotc, "tags": tag, "f1": f1, "f2": f2, "f3": f3, "f4": f4}
    return newf


def homepage(request):
    newc = getIndexContent()
    return render(request, 'article/index.html', newc)


def user_login(request):
    reg_form = RegisterForm()
    code_form = IdenCodeForm()
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['user_name'], password=cd['password'])
            if user is not None and user.is_active:
                login(request, user)
                return HttpResponseRedirect('../')
            else:
                err_msg = '1'
                return render(request, "article/register.html",
                              {"form": login_form, "err": err_msg,"regForm": reg_form, "codeForm": code_form})
        else:
            err_msg = '1'
            return render(request, "article/register.html",
                          {"form": login_form, "err": err_msg,"regForm": reg_form, "codeForm": code_form})
    if request.method == "GET":
        login_form = LoginForm()
        err_msg = '5'
        return render(request, "article/register.html",
                      {"form": login_form, "err":err_msg, "regForm": reg_form, "codeForm": code_form})


@login_required(login_url='register/login')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('../')


def iden_code_data():
    lowercase = 'abcdefghijklmnopqrstuvwxyz'
    uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    numcase = '0123456789'
    i = 0
    code_data = ''
    while i < 6:
        num = random.choice([0, 1, 2])
        if num == 0:
            code = random.choice(lowercase)
        elif num == 1:
            code = random.choice(uppercase)
        else:
            code = random.choice(numcase)
        code_data += code
        i += 1
    return code_data


def post_email(request):
    if request.method == "POST":
        username = request.POST.get('name')
        email_addr = request.POST.get('email')
        str = r'^[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){0,4}@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){0,4}$'
        if re.match(str, email_addr) is None:
            status = '0'
            return HttpResponse(json.dumps({"status": status}))
        else:
            status = '2'
            code_data = iden_code_data()
            request.session[username] = code_data
            request.session.set_expiry(60 * 5)
            message = '\n\n师生互动社区注册验证码是：' + code_data + '\n有效时间5分钟，超时需重新获取验证码\n如非本人操作，请勿泄露！'
            send_mail('师生互动社区注册验证码', message, 'leowle@126.com', [email_addr], fail_silently=False)
            return HttpResponse(json.dumps({"status": status}))


def register(request):
    login_form = LoginForm()
    if request.method == "GET":
        reg_form = RegisterForm()
        code_form = IdenCodeForm()
        return render(request, "article/register.html",
                      {"regForm": reg_form, "codeForm": code_form,"form": login_form})
    elif request.method == "POST":
        reg_form = RegisterForm(request.POST)
        code_form = IdenCodeForm(request.POST)
        if reg_form.is_valid() * code_form.is_valid():
            cd = code_form.cleaned_data['iden_code']
            try:
                if cd == request.session[reg_form.cleaned_data['username']]:
                    del request.session[reg_form.cleaned_data['username']]
                    newuser = reg_form.save(commit=False)
                    newuser.set_password(reg_form.cleaned_data['password'])
                    newuser.save()
                    PersonalInfo.objects.create(user=newuser)
                    err_msg = '3'
                    return render(request, "article/register.html",
                                  {"regForm": reg_form, "codeForm": code_form, "err": err_msg,"form": login_form})
                else:
                    del request.session[reg_form.cleaned_data['username']]
                    err_msg = '2'
                    return render(request, "article/register.html",
                                  {"regForm": reg_form, "codeForm": code_form, "err": err_msg,"form": login_form})
            except Exception as e:
                print(e)
                err_msg = '4'
                return render(request, "article/register.html",
                              {"regForm": reg_form, "codeForm": code_form, "err": err_msg,"form": login_form})
        else:
            err_msg = '4'
            return render(request, "article/register.html",
                          {"regForm": reg_form, "codeForm": code_form, "err": err_msg,"form": login_form})


def post_email_login(request):
    if request.method == 'POST':
        username = request.POST.get('name')
        try:
            status = '1'
            email_addr= User.objects.get(username__exact=username).email
            code_data = iden_code_data()
            request.session[username] = code_data
            request.session.set_expiry(60 * 5)
            message = '\n\n师生互动社区登陆验证码是：' + code_data + '\n有效时间5分钟，超时需重新获取验证码\n如非本人操作，请勿泄露！'
            send_mail('师生互动社区注册验证码', message, 'leowle@126.com', [email_addr], fail_silently=False)
            return HttpResponse(json.dumps({"status": status}))
        except User.DoesNotExist:
            status = '0'
            return HttpResponse(json.dumps({"status": status}))


class EmailBackend(ModelBackend):
    def authenticate(self, request, username=None, cd=None, rcd=None, **kwargs):
        try:
            user = User.objects.get(username=username)
            if cd == rcd:
                return user
        except Exception as e:  #可以捕获除与程序退出sys.exit()相关之外的所有异常
            print(e)
            return None


def emailLogin(request):
    if request.method == 'GET':
        emaiLoForm = EmailLoginForm()
        return render(request, "article/emailfind.html", {"emaiLoForm": emaiLoForm})
    if request.method == 'POST':
        emaiLoForm = EmailLoginForm(request.POST)
        if emaiLoForm.is_valid():
            cd = emaiLoForm.cleaned_data['code']
            rcd = request.session[emaiLoForm.cleaned_data['user_name']]
            del request.session[emaiLoForm.cleaned_data['user_name']]
            user = authenticate(username=emaiLoForm.cleaned_data['user_name'], cd=cd, rcd=rcd)
            if user is not None and user.is_active:
                login(request, user)
                return HttpResponseRedirect('../')
            else:
                errmsg = '1'
                return render(request, "article/emailfind.html",
                              {"emaiLoForm": emaiLoForm, "err": errmsg})
        else:
            errmsg = '0'
            return render(request, "article/emailfind.html",
                          {"emaiLoForm": emaiLoForm, "err": errmsg})


def handle_upload_file(file):
    timenow = time.localtime(time.time())
    timenow = time.strftime("%Y-%m-%d",timenow)
    path='media/'+str(timenow) + "/"
                                      #上传文件的保存路径，可以自己指定任意的路径
    savepath = str(timenow)+"/"
    if not os.path.exists(path):
        os.makedirs(path)
    with open(path + file.name, 'wb+')as destination:
        for chunk in file.chunks():
            destination.write(chunk)
    return savepath+file.name


@login_required(login_url='register/login')
def publishArticle(request):
    if request.method == 'GET':
        pform = AriclesForm()
        return render(request, "article/newarticle.html", {"pform": pform})
    if request.method == 'POST':
        pform = AriclesForm(request.POST, request.FILES)
        if pform.is_valid():
            title = pform.cleaned_data['title']
            category = pform.cleaned_data['category']
            abstract = pform.cleaned_data['abstract']
            attachment = pform.cleaned_data['attachment']
            body = pform.cleaned_data['body']
            article = Articles()
            article.title = title
            article.author_id = request.user.id
            article.category = category
            article.abstract = abstract
            myfile = request.FILES.get("attachment", None)
            if myfile:
                attachment = handle_upload_file(myfile)
            article.attachment = attachment
            article.body = body
            article.save()
            return HttpResponseRedirect('../')
        else:
            return render(request, "article/newarticle.html", {"pform": pform})


def article(request,article_id):
    artcon = Articles.objects.get(id=article_id)
    artcon.views += 1
    artcon.save()
    comments = Comments.objects.filter(artid=article_id)
    reply = CommentsReply.objects.filter(art_id=article_id)
    path = str(artcon.attachment)
    filename = None
    fp = False
    if path:
        filename = path.split("/")[1]
        filetype = filename.split(".")[1]
        if filetype == 'pdf':
            fp = True
    is_collected = False
    if(artcon.collects.filter(id=request.user.id)):
        is_collected = True
    art = {
        "art": artcon,
        "is_collected": is_collected,
        "filename": filename,
        "ft": fp,
        "comments": comments,

templates/article/showarticle.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>师生互动社区</title>
	<link rel="stylesheet" type="text/css" href="../../static/css/index.css"/>
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/bootstrap.min.css"/>
</head>
<body>
	<div class="header">
		<div class="logo">
            <a href="{% url 'article:index' %}"><img src="../../static/img/logo.png"/></a>
			<span>许多东西都因不发问而丧失</span>
		</div>
		<div class="serarch-box">
			<form class="serarch-form" role="search" action="search" method="post">{% csrf_token %}
				<input class="" type="text" name="words" placeholder="站内搜索"/>
				<button type="submit" value="search" class="search-btn" id="">
					<span class="glyphicon glyphicon-search"></span>
				</button>
			</form>
		</div>
		<div class="user-state">
            {% if user.is_authenticated %}
             <ul class="logined">
				<li><img src="../../static/img/head.jpg"/><a>{{ user.username }}</a></li>
			</ul>
            {% else %}
            <ul class="not-login">
				<li><a href="{% url 'article:user_login' %}">登陆</a></li>
				<li><a href="{% url 'article:user_register' %}">注册</a></li>
			</ul>
            {% endif %}
			<div class="set-view">
				<div class="postings">
					<ul>
						<li><a href="{% url 'article:new_article' %}"><img src="../../static/img/comment.svg"/><p>发帖</p></a></li>
						<li><a href="{% url 'article:myarticle' %}"><img src="../../static/img/text.svg"/><p>我的帖子</p></a></li>
						<li><a href="{% url 'article:mycollect' %}"><img src="../../static/img/collect.svg"/><p>我的收藏</p></a></li>
					</ul>
				</div>
				<div class="single-info">
					<ul>
						<li><a href="{% url 'article:myinfomation' %}">个人资料</a></li>
						<li><a href="{% url 'article:user_logout' %}">退出登陆</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="bbs">
		<div class="abs">
			<div class="abs-top">
				<p class="crumbs">
					<a href="{% url 'article:index' %}">师生交流社区</a>&nbsp;&gt;&nbsp;
					<a href="{% url 'article:article_list' art.category_id %}">{{ art.category }}</a>
				</p>
			</div>
			<div class="abs-title" data="{{ art.id }}">
				<p>{{ art.title }}</p>
			</div>
			<div class="abs-extra">
				<ul>
					<li><span class="glyphicon glyphicon-user"><span>{{ art.author }}</span></span></li>
					<li><span class="glyphicon glyphicon-time"><span>{{ art.created_time|date:"Y-m-d" }}</span></span></li>
					<li><span class="glyphicon glyphicon-eye-open"><span>{{ art.views }}次浏览</span></span></li>
					<li><span class="glyphicon glyphicon-tags"><span>{{ art.comments }}条评论</span></span></li>
				</ul>
			</div>
			<div class="abs-ct">
                {% autoescape off %}
                    {{ art.body }}
                {% endautoescape %}
			</div>
            {% if art.attachment %}
                <div class="file-upload">
                    <img src="../../static/img/file.svg" alt="">
                    <span>{{ filename }}</span>
                    <span><a href="{% url 'article:download' art.id %}">下载</a></span>
                    {% if ft %}
                        <span class="prevpdf"><a href="{{ art.attachment.url }}" target="pdfContainer" >预览</a></span>
                    {% endif %}
                </div>
                <div id="pop" class="pop" style="display: none;">
                    <iframe src="" frameborder="0" id="pdfContainer" name="pdfContainer"></iframe>
                </div>
            {% endif %}

			<div class="abs-com">
				<div class="com-menu">
					<ul>
                        {% if user.is_authenticated %}
                            <li>
                                <button>评论</button>
                                <a class="collect" href="javacrript:void(0);">
                                    {% if is_collected %}
                                        <span style="color: hotpink" class="glyphicon glyphicon-heart"></span>
                                    {% else %}
                                        <span style="color: #6699cc" class="glyphicon glyphicon-heart"></span>
                                    {% endif %}
                                </a>
                            </li>
                        {% else %}
						    <li>登录后可以评论收藏哦,赶快<a href="{% url 'article:user_login' %}">登陆</a>吧</li>
					    {% endif %}
                    </ul>
				</div>
				<div class="com-input">
					<form action="" method="post">{% csrf_token %}
						<textarea name="" placeholder="请写点什么吧……"></textarea><br />
						<input class="postcom" type="submit" value="发表评论"/>
					</form>
				</div>
				<div class="abs-show-com">
					<div class="com-info-top">
						<div class="com-info-left">
							评论
						</div>
						<div class="com-info-right">
						</div>
						<div class="com-info">
							<ul>
                                {% if comments %}
                                    {% for com in comments %}
                                        <li class="comments" data="{{ com.id }}">
                                            <div class="com-auth">
                                                <p>
                                                    <span data="{{ com.author_id }}">{{ com.author }}</span>
                                                </p>
                                            </div>
                                            <div class="com-info-ct" data-actions-icnt="">
                                                {{ com.content }}
                                                {% for rep in reply %}
                                                    {% ifequal com.id rep.comment_id %}
                                                        <div class="reply">
                                                            <div class="reply-auth">
                                                                <p>
                                                                    <span data="{{ rep.author_id_id }}">{{ rep.author_id }}</span>
                                                                    <span class="rek">回复</span>
                                                                    <span class="rrauth">{{ rep.author_to }}</span>
                                                                </p>
                                                            </div>
                                                            <div class="reply-info">
                                                                {{ rep.content }}
                                                            </div>
                                                            {% if user.is_authenticated %}
                                                                <a class="btn-reply" href="javascript:void(0);">回复</a>
                                                                <div class="com-input" style="display: none">
                                                                    <form action="" method="post">{% csrf_token %}
                                                                        <textarea name="" placeholder="请写点什么吧……"></textarea><br />
                                                                        <input class="postreply r1" type="submit" value="发表回复"/>
                                                                    </form>
                                                                </div>
                                                            {% endif %}
                                                        </div>
                                                    {% endifequal %}
                                                {% endfor %}
                                            </div>
                                            {% if user.is_authenticated %}
                                                <a class="btn-reply" href="javascript:void(0);">回复</a>
                                                <div class="com-input" style="display: none">
                                                    <form action="" method="post">{% csrf_token %}
                                                        <textarea name="" placeholder="请写点什么吧……"></textarea><br />
                                                        <input class="postreply r2" type="submit" value="发表回复"/>
                                                    </form>
                                                </div>
                                            {% endif %}
                                        </li>
                                    {% endfor %}
                                {% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="footer">
		@ 2007 - 2018 师生互动社区
	</div>

	<script src="../../static/js/jquery-3.1.0.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://cdn.bootcss.com/pdf.js/2.0.480/pdf.min.js"></script>
	<script src="../../static/js/bootstrap.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="https://unpkg.com/wangeditor@3.1.0/release/wangEditor.min.js"></script>
	<script src="../../static/js/index.js" type="text/javascript" charset="utf-8"></script>
	<script src="../../static/js/editor.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" charset="UTF-8">
    $(function(){
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });

        $(".com-menu > ul > li > .collect").on("click",collected)
        $(".postcom").on("click",comment)
        $(".postreply").on("click",reply)

        function collected() {
            var article = $(".abs-title").attr("data")
            var postdata = {
                'article':article
            }
            console.log(postdata)
            $.ajax({
                url:'{% url 'article:collected' %}',
                type:'POST',
                dataType:'json',
                data:postdata,
                success:function (data) {
                    if(data['status'] =='0'){
                        $(".com-menu > ul > li > a > span").css({
                            "color":"#69c"
                        })
                    }else if(data['status']=='1'){
                        $(".com-menu > ul > li > a > span").css({
                            "color":"hotpink"
                        })
                    }
                }
            })
            return false
        }
        
        function comment(e) {
            e= e || window.e
            e.preventDefault()
            var art_id = $(".abs-title").attr("data")
            var content = $(this).siblings("textarea").val()
            if(content.length == 0){
                alert("回复不能为空")
                return false
            }
            var postdata = {
                'article':art_id,
                'content':content
            }
            $.ajax({
                url:'{% url 'article:submitcomment' %}',
                type:'POST',
                dataType:'json',
                data:postdata,
                success:function (data) {
                    window.location.reload()
                }
            })
        }

        function reply(e) {
            e= e || window.e
            e.preventDefault()
            var art_id = $(".abs-title").attr("data")
            var content = $(this).siblings("textarea").val()
            var com_id = $(this).parents().filter(".comments").attr("data")
            if($(this).hasClass("r2")){
                var author_to = $(this).parentsUntil(".comments").filter(".com-input").siblings(".com-auth").find("p > span").attr("data")
            }else {
                var author_to = $(this).parentsUntil(".reply").siblings(".reply-auth").find("p > span:first").attr("data")
            }
            if(content.length == 0){
                alert("回复不能为空")
                return false
            }
            var postdata = {
                'article':art_id,
                'content':content,
                'comment':com_id,
                'author_to':author_to
            }
            $.ajax({
                url:'{% url 'article:submitreply' %}',
                type:'POST',
                dataType:'json',
                data:postdata,
                success:function (data) {
                    if(data['status'] == '0'){
                        alert("不能回复自己")
                        window.location.reload()
                    }else {
                        window.location.reload()
                    }
                }
            })
        }


    })
    </script>
</body>
</html>

templates/article/showartlist.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>师生互动社区</title>
	<link rel="stylesheet" type="text/css" href="../../static/css/index.css"/>
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/bootstrap.min.css"/>
</head>
<body onload="changeCurLeftNav()">
	<div class="header">
		<div class="logo">
            <a href="{% url 'article:index' %}"><img src="../../static/img/logo.png"/></a>
			<span>许多东西都因不发问而丧失</span>
		</div>
		<div class="serarch-box">
			<form class="serarch-form" role="search" action="search" method="post">{% csrf_token %}
				<input class="" type="text" name="words" placeholder="站内搜索"/>
				<button type="submit" value="search" class="search-btn" id="">
					<span class="glyphicon glyphicon-search"></span>
				</button>
			</form>
		</div>
		<div class="user-state">
            {% if user.is_authenticated %}
             <ul class="logined">
				<li><img src="../../static/img/head.jpg"/><a>{{ user.username }}</a></li>
			</ul>
            {% else %}
            <ul class="not-login">
				<li><a href="{% url 'article:user_login' %}">登陆</a></li>
				<li><a href="{% url 'article:user_register' %}">注册</a></li>
			</ul>
            {% endif %}
			<div class="set-view">
				<div class="postings">
					<ul>
						<li><a href="{% url 'article:new_article' %}"><img src="../../static/img/comment.svg"/><p>发帖</p></a></li>
						<li><a href="{% url 'article:myarticle' %}"><img src="../../static/img/text.svg"/><p>我的帖子</p></a></li>
						<li><a href="{% url 'article:mycollect' %}"><img src="../../static/img/collect.svg"/><p>我的收藏</p></a></li>
					</ul>
				</div>
				<div class="single-info">
					<ul>
						<li><a href="{% url 'article:myinfomation' %}">个人资料</a></li>
						<li><a href="{% url 'article:user_logout' %}">退出登陆</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="bbs">
		<div class="left-nav">
			<ul>
				<li><a href="{% url 'article:index' %}">社区首页</a></li>
                {% for tag in tags %}
                    <li><a href="{% url 'article:article_list' tag.id %}">{{ tag.name }}</a></li>
                {% endfor %}
			</ul>
		</div>
		<div class="content">
			<div class="bbc">
				<ul>
                    {% for art in artlist %}
                        <li class="blhover">
                            <div class="art-name">
                                <a href="{% url 'article:show_article' art.id %}">{{ art.title }}</a>
                            </div>
                            <div class="art-detail">
                                <p>{{ art.abstract }}</p>
                            </div>
                            <div class="art-extra">
                                <ul>
                                    <li><span class="glyphicon glyphicon-user"><span>{{ art.author }}</span></span></li>
                                    <li><span class="glyphicon glyphicon-time"><span>{{ art.created_time|date:"Y-m-d" }}</span></span></li>
                                    <li><span class="glyphicon glyphicon-eye-open"><span>{{ art.views }}次浏览</span></span></li>
                                    <li><span class="glyphicon glyphicon-tags"><span>{{ art.comments }}条评论</span></span></li>
                                </ul>
                            </div>
                        </li>
					{% endfor %}

				</ul>
			</div>

		</div>
	</div>
	<div class="footer">
		@ 2007 - 2018 师生互动社区
	</div>


	<script src="../../static/js/jquery-3.1.0.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="../../static/js/bootstrap.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="https://unpkg.com/wangeditor@3.1.0/release/wangEditor.min.js"></script>
	<script src="../../static/js/index.js" type="text/javascript" charset="utf-8"></script>
	<script src="../../static/js/editor.js" type="text/javascript" charset="utf-8"></script>
</body>
</html>